
name: 🚀 Doxygen

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'


jobs:
  run:
    name: 🚀 Run
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Init
        shell: bash
        run: |
          sudo apt install doxygen
      - name: 🚀 Run Tests
        shell: bash
        run: |
          python3 -m unittest
      - name: Run doxygen
        shell: bash
        run: |
          doxygen
      - name: Upload doxygen
        uses: actions/upload-artifact@v3.0.0
        with:
          name: cciulacu-doxygen
          path: html/*